using Microsoft.EntityFrameworkCore;
using WebShopABMATIC.Data.Entities;

namespace WebShopABMATIC.Data.Persistence;

public class WebShopABMATICDbContext : DbContext
{
    public WebShopABMATICDbContext(DbContextOptions<WebShopABMATICDbContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        new WebShopABMATICModelBuilder().BuildModel(modelBuilder);
    }

    public DbSet<AccountingDocument> AccountingDocuments { get; set; } = null!;
    public DbSet<AccountingDocumentLine> AccountingDocumentLines { get; set; } = null!;
    public DbSet<Activity> Activities { get; set; } = null!;
    public DbSet<AppError> AppErrors { get; set; } = null!;
    public DbSet<AppSetting> AppSettings { get; set; } = null!;
    public DbSet<AutoNumbering> AutoNumberings { get; set; } = null!;
    public DbSet<AzureFile> AzureFiles { get; set; } = null!;
    public DbSet<AzureFileFolder> AzureFileFolders { get; set; } = null!;
    public DbSet<BaseCompany> BaseCompanies { get; set; } = null!;
    public DbSet<BaseCompanyAcces> BaseCompanyAcceses { get; set; } = null!;
    public DbSet<BaseCompanyVatNumber> BaseCompanyVatNumbers { get; set; } = null!;
    public DbSet<BillingAgreement> BillingAgreements { get; set; } = null!;
    public DbSet<CalendarEntry> CalendarEntries { get; set; } = null!;
    public DbSet<CalendarLabel> CalendarLabels { get; set; } = null!;
    public DbSet<CalendarLog> CalendarLogs { get; set; } = null!;
    public DbSet<CalendarStatus> CalendarStatuses { get; set; } = null!;
    public DbSet<City> Cities { get; set; } = null!;
    public DbSet<Contact> Contacts { get; set; } = null!;
    public DbSet<ContactProjectRole> ContactProjectRoles { get; set; } = null!;
    public DbSet<Country> Countries { get; set; } = null!;
    public DbSet<Customer> Customers { get; set; } = null!;
    public DbSet<CustomerContact> CustomerContacts { get; set; } = null!;
    public DbSet<CustomerCustomProduct> CustomerCustomProducts { get; set; } = null!;
    public DbSet<CustomerCustomProductLine> CustomerCustomProductLines { get; set; } = null!;
    public DbSet<CustomerCustomProductTier> CustomerCustomProductTiers { get; set; } = null!;
    public DbSet<CustomerDeliveredProduct> CustomerDeliveredProducts { get; set; } = null!;
    public DbSet<CustomerDeliveryAddress> CustomerDeliveryAddresses { get; set; } = null!;
    public DbSet<CustomerExtraDiscount> CustomerExtraDiscounts { get; set; } = null!;
    public DbSet<CustomerFollowUp> CustomerFollowUps { get; set; } = null!;
    public DbSet<CustomerJobCodeRate> CustomerJobCodeRates { get; set; } = null!;
    public DbSet<CustomerNote> CustomerNotes { get; set; } = null!;
    public DbSet<CustomerOrderStatusRemark> CustomerOrderStatusRemarks { get; set; } = null!;
    public DbSet<CustomerProductDiscount> CustomerProductDiscounts { get; set; } = null!;
    public DbSet<CustomerStatus> CustomerStatuses { get; set; } = null!;
    public DbSet<CustomerSupplierDiscount> CustomerSupplierDiscounts { get; set; } = null!;
    public DbSet<CustomerType> CustomerTypes { get; set; } = null!;
    public DbSet<DeliveryType> DeliveryTypes { get; set; } = null!;
    public DbSet<DocumentTemplate> DocumentTemplates { get; set; } = null!;
    public DbSet<DocumentType> DocumentTypes { get; set; } = null!;
    public DbSet<DrawGroup> DrawGroups { get; set; } = null!;
    public DbSet<EmailAttachment> EmailAttachments { get; set; } = null!;
    public DbSet<EmailMessage> EmailMessages { get; set; } = null!;
    public DbSet<EmailQueue> EmailQueues { get; set; } = null!;
    public DbSet<GridLayout> GridLayouts { get; set; } = null!;
    public DbSet<IntrastatCode> IntrastatCodes { get; set; } = null!;
    public DbSet<IntrastatReportLine> IntrastatReportLines { get; set; } = null!;
    public DbSet<JobCode> JobCodes { get; set; } = null!;
    public DbSet<JobSite> JobSites { get; set; } = null!;
    public DbSet<Language> Languages { get; set; } = null!;
    public DbSet<LanguageTag> LanguageTags { get; set; } = null!;
    public DbSet<MaintenanceContract> MaintenanceContracts { get; set; } = null!;
    public DbSet<MaintenanceContractLine> MaintenanceContractLines { get; set; } = null!;
    public DbSet<Manufacturer> Manufacturers { get; set; } = null!;
    public DbSet<MiscellaneousProduct> MiscellaneousProducts { get; set; } = null!;
    public DbSet<Order> Orders { get; set; } = null!;
    public DbSet<OrderAdvancePayment> OrderAdvancePayments { get; set; } = null!;
    public DbSet<OrderDeliveryTypeProduct> OrderDeliveryTypeProducts { get; set; } = null!;
    public DbSet<OrderDevelopmentLine> OrderDevelopmentLines { get; set; } = null!;
    public DbSet<OrderFeedback> OrderFeedbacks { get; set; } = null!;
    public DbSet<OrderFileLink> OrderFileLinks { get; set; } = null!;
    public DbSet<OrderInstallationLine> OrderInstallationLines { get; set; } = null!;
    public DbSet<OrderLine> OrderLines { get; set; } = null!;
    public DbSet<OrderLineText> OrderLineTexts { get; set; } = null!;
    public DbSet<OrderLog> OrderLogs { get; set; } = null!;
    public DbSet<OrderProcessingType> OrderProcessingTypes { get; set; } = null!;
    public DbSet<OrderProjectLine> OrderProjectLines { get; set; } = null!;
    public DbSet<OrderRemark> OrderRemarks { get; set; } = null!;
    public DbSet<OrderStatus> OrderStatuses { get; set; } = null!;
    public DbSet<OrderStatusAccess> OrderStatusAccesses { get; set; } = null!;
    public DbSet<OrderStatusGroup> OrderStatusGroups { get; set; } = null!;
    public DbSet<OrderStructure> OrderStructures { get; set; } = null!;
    public DbSet<OrderTemplate> OrderTemplates { get; set; } = null!;
    public DbSet<OrderTemplateDetail> OrderTemplateDetails { get; set; } = null!;
    public DbSet<OrderType> OrderTypes { get; set; } = null!;
    public DbSet<PaymentMethod> PaymentMethods { get; set; } = null!;
    public DbSet<PaymentTerm> PaymentTerms { get; set; } = null!;
    public DbSet<PriceListCategory> PriceListCategories { get; set; } = null!;
    public DbSet<PriceListText> PriceListTexts { get; set; } = null!;
    public DbSet<Product> Products { get; set; } = null!;
    public DbSet<ProductDiscountSuggestion> ProductDiscountSuggestions { get; set; } = null!;
    public DbSet<ProductDiscountSuggestionLine> ProductDiscountSuggestionLines { get; set; } = null!;
    public DbSet<ProductManual> ProductManuals { get; set; } = null!;
    public DbSet<ProductOption> ProductOptions { get; set; } = null!;
    public DbSet<ProductOptionValue> ProductOptionValues { get; set; } = null!;
    public DbSet<ProductPopupReturnColumn> ProductPopupReturnColumns { get; set; } = null!;
    public DbSet<ProductPopupTemplate> ProductPopupTemplates { get; set; } = null!;
    public DbSet<ProductPopupTemplateLine> ProductPopupTemplateLines { get; set; } = null!;
    public DbSet<ProductPopupValueType> ProductPopupValueTypes { get; set; } = null!;
    public DbSet<ProductPrice> ProductPrices { get; set; } = null!;
    public DbSet<ProductPriceSalesDiscount> ProductPriceSalesDiscounts { get; set; } = null!;
    public DbSet<ProductProductionGroup> ProductProductionGroups { get; set; } = null!;
    public DbSet<ProductProductionGroupLink> ProductProductionGroupLinks { get; set; } = null!;
    public DbSet<ProductProperty> ProductProperties { get; set; } = null!;
    public DbSet<ProductPropertyItem> ProductPropertyItems { get; set; } = null!;
    public DbSet<ProductPurchaseDiscount> ProductPurchaseDiscounts { get; set; } = null!;
    public DbSet<ProductQuantityTier> ProductQuantityTiers { get; set; } = null!;
    public DbSet<ProductStockLocation> ProductStockLocations { get; set; } = null!;
    public DbSet<ProductStructure> ProductStructures { get; set; } = null!;
    public DbSet<ProductSubProduct> ProductSubProducts { get; set; } = null!;
    public DbSet<ProductType> ProductTypes { get; set; } = null!;
    public DbSet<ProductUnit> ProductUnits { get; set; } = null!;
    public DbSet<Project> Projects { get; set; } = null!;
    public DbSet<ProjectActivity> ProjectActivities { get; set; } = null!;
    public DbSet<ProjectContact> ProjectContacts { get; set; } = null!;
    public DbSet<ProjectInstallation> ProjectInstallations { get; set; } = null!;
    public DbSet<ProjectLog> ProjectLogs { get; set; } = null!;
    public DbSet<ProjectParty> ProjectParties { get; set; } = null!;
    public DbSet<ProjectPartyContact> ProjectPartyContacts { get; set; } = null!;
    public DbSet<ProjectPartyGroup> ProjectPartyGroups { get; set; } = null!;
    public DbSet<RawMaterial> RawMaterials { get; set; } = null!;
    public DbSet<RepairCostPrice> RepairCostPrices { get; set; } = null!;
    public DbSet<ReportingGroup> ReportingGroups { get; set; } = null!;
    public DbSet<Salutation> Salutations { get; set; } = null!;
    public DbSet<ServiceRate> ServiceRates { get; set; } = null!;
    public DbSet<SickLeave> SickLeaves { get; set; } = null!;
    public DbSet<StaffUser> StaffUsers { get; set; } = null!;
    public DbSet<StandardBillingTerm> StandardBillingTerms { get; set; } = null!;
    public DbSet<StandardBillingTermLine> StandardBillingTermLines { get; set; } = null!;
    public DbSet<StockLocation> StockLocations { get; set; } = null!;
    public DbSet<StockMovement> StockMovements { get; set; } = null!;
    public DbSet<StockOrder> StockOrders { get; set; } = null!;
    public DbSet<StockOrderDelivery> StockOrderDeliveries { get; set; } = null!;
    public DbSet<StockOrderLine> StockOrderLines { get; set; } = null!;
    public DbSet<StoredFile> StoredFiles { get; set; } = null!;
    public DbSet<Supplier> Suppliers { get; set; } = null!;
    public DbSet<SupplierContact> SupplierContacts { get; set; } = null!;
    public DbSet<TaskAction> TaskActions { get; set; } = null!;
    public DbSet<TaskDependency> TaskDependencies { get; set; } = null!;
    public DbSet<TaskItem> TaskItems { get; set; } = null!;
    public DbSet<TaskTemplate> TaskTemplates { get; set; } = null!;
    public DbSet<TaskTemplateDependency> TaskTemplateDependencies { get; set; } = null!;
    public DbSet<TaskTemplateTask> TaskTemplateTasks { get; set; } = null!;
    public DbSet<TaskType> TaskTypes { get; set; } = null!;
    public DbSet<TemplateType> TemplateTypes { get; set; } = null!;
    public DbSet<Timesheet> Timesheets { get; set; } = null!;
    public DbSet<UserGroup> UserGroups { get; set; } = null!;
    public DbSet<VatType> VatTypes { get; set; } = null!;
    public DbSet<WebshopProductStructure> WebshopProductStructures { get; set; } = null!;
    public DbSet<WebshopStructure> WebshopStructures { get; set; } = null!;
}

