#nullable enable
using System;

namespace WebShopABMATIC.Data.Entities;

/// <summary>Entity for [Projects].[OrderLines] (legacy: [Projecten].[BestellingDetail]).</summary>
public class OrderLine
{
    public int Id { get; set; }
    public int OrderId { get; set; }
    public int? GateId { get; set; }
    public int? ProductId { get; set; }
    public decimal Quantity { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal AssemblyPrice { get; set; }
    public decimal InstallationPrice { get; set; }
    public decimal TotalExclVat { get; set; }
    public decimal TotalInclVat { get; set; }
    public bool IsOption { get; set; }
    public decimal Discount { get; set; }
    public decimal Btw { get; set; }
    public string UpliftType { get; set; }
    public string DocumentDisplayName { get; set; }
    public decimal Lengte { get; set; }
    public decimal Hoogte { get; set; }
    public decimal Breedte { get; set; }
    public bool Assemblage { get; set; }
    public bool Montage { get; set; }
    public string QuoteNotesHeader { get; set; }
    public string? ProductionNotes { get; set; }
    public decimal MontageStukprijs { get; set; }
    public decimal AssemblageStukprijs { get; set; }
    public int? ProductOptionId { get; set; }
    public int? ProductOptionHoofdDetaillId { get; set; }
    public string? SerialNumber { get; set; }
    public string ProductionGroupId { get; set; }
    public decimal? AantalProductieVerwerkt { get; set; }
    public decimal? AantalAfgehaaldOfGeleverd { get; set; }
    public decimal? QuantityInvoiced { get; set; }
    public bool? Afgehandeld { get; set; }
    public string PurchaseOrderNotes { get; set; }
    public string? PopUpDataXml { get; set; }
    public int ProductType { get; set; }
    public bool? InProductie { get; set; }
    public bool? Controleren { get; set; }
    public bool? ProductieKlaar { get; set; }
    public bool? LeveringOfAfhalingKlaar { get; set; }
    public bool? MontageKlaar { get; set; }
    public bool? Gefactureerd { get; set; }
    public bool? Tefactureren { get; set; }
    public DateTime? ProductieVerwerkOp { get; set; }
    public DateTime? ReadyForBillingDate { get; set; }
    public decimal BtwBedrag { get; set; }
    public int SortOrder { get; set; }
    public bool? Tecrediteren { get; set; }
    public DateTime? GecrediteerdOp { get; set; }
    public bool? ToOrder { get; set; }
    public bool? Ordered { get; set; }
    public DateTime? OrderedDate { get; set; }
    public string DocumentDisplayNameFr { get; set; }
    public decimal? NettoCommisieEenheidsPrijs { get; set; }
    public bool? IsSubProduct { get; set; }
    public decimal AantalSubProduct { get; set; }
    public string? BestelNummer { get; set; }
    public int? SupplierId { get; set; }
    public decimal? PurchasePrice { get; set; }
    public int? ProductEenheidId { get; set; }
    public DateTime? InvoicedAt { get; set; }
    public bool? PrijsControleren { get; set; }
    public decimal AantalTeBestellen { get; set; }
    public int? ProductStockLocatieId { get; set; }
    public decimal? AantalInStockGereserveerd { get; set; }
    public decimal? AantalDefinitiefUitStock { get; set; }
    public bool? NoPriceCacl { get; set; }
    public decimal? AantalBeschikbaarInStock { get; set; }
    public bool? IsSamenGesteldProduct { get; set; }
    public int ReportingGroupId { get; set; }
    public decimal BrutoAankoopprijs { get; set; }
    public decimal NettoAankoopPrijs { get; set; }
    public decimal WinstPercentage { get; set; }
    public int? StockOrderDetailId { get; set; }
    public decimal? QuantityOrdered { get; set; }
    public DateTime? OrderedAt { get; set; }
    public string? ArticleNumber { get; set; }
    public decimal OrigineleKorting { get; set; }
    public bool? OverRuleLosseLijnAutoKorting { get; set; }
    public bool? IsTextOnly { get; set; }
    public string UpliftTypeOrigineel { get; set; }
    public decimal BasePrice { get; set; }
    public string? BebatNaam { get; set; }
    public int? BebatProductId { get; set; }
    public string? RecupelNaam { get; set; }
    public int? RecupelProductId { get; set; }
    public decimal BebatAantal { get; set; }
    public decimal BebatStukPrijs { get; set; }
    public decimal BebatTotaal { get; set; }
    public decimal RecupelAantal { get; set; }
    public decimal RecupelStukPrijs { get; set; }
    public decimal RecupelTotaal { get; set; }
    public bool? IsProducedCompositeProduct { get; set; }
    public bool? IsLeveringsTypeProduct { get; set; }
    public string? StandaardKortingsType { get; set; }
    public decimal? StandaardKortingsPecentage { get; set; }
    public bool IsGarantie { get; set; }
    public decimal TotaalExclVoorCommissie { get; set; }
    public bool PopUpRow { get; set; }
    public int? NodeLevel { get; set; }
    public DateTime? AfgehandeldOp { get; set; }
    public bool Selected { get; set; }
    public bool? IsExtraKortingRow { get; set; }
    public bool? BestellingIsBinnenGekomen { get; set; }
    public decimal UnitParameter { get; set; }
    public bool BasisPrijsTellen { get; set; }
    public bool ShowOnQuote { get; set; }
    public bool ShowOnOrderConfirmation { get; set; }
    public bool ShowOnInvoice { get; set; }
    public bool ShowOnPackingSlip { get; set; }
    public bool ShowOnDeliveryNote { get; set; }
    public bool ShowOnProductionOrder { get; set; }
    public bool ToonOpLakBon { get; set; }
    public bool ShowOnInstallationOrder { get; set; }
    public string? Ral { get; set; }
    public bool ToonOmschrijvingOpFactuur { get; set; }
    public bool ToonOmschrijvingOpPakbon { get; set; }
    public bool ToonOmschrijvingOpLeverbon { get; set; }
    public bool ToonOmschrijvingOpProductiebon { get; set; }
    public bool ToonOmschrijvingOpLakBon { get; set; }
    public bool ToonOmschrijvingOpOfferte { get; set; }
    public bool ToonOpVrachtbrief { get; set; }
    public bool ToonOmschrijvingOpVrachtbrief { get; set; }
    public bool ToonOmschrijvingOpOrderbevestiging { get; set; }
    public decimal StartupCost { get; set; }
    public decimal OpstartKostTotaal { get; set; }
    public decimal BasisPrijsTotaal { get; set; }
    public int VatTypeId { get; set; }
    public int? OrderTemplateId { get; set; }
    public int? OrderTemplateDetailId { get; set; }
    public decimal PieceUnitPrice { get; set; }
    public int? CustomerCustomProductId { get; set; }
    public bool? TaxproductenGecontroleerd { get; set; }
    public bool ReportRecupel { get; set; }
    public bool ReportBebat { get; set; }
    public bool? ToonGeenDetailPrijzen { get; set; }
    public int? OfferteDocumentDocId { get; set; }
    public int? OrderBevestigingDocumentDocId { get; set; }
    public int? PakBonDocumentDocId { get; set; }
    public int? LeveringsBonDocId { get; set; }
    public int? FactuurDocId { get; set; }
    public bool? IsProduction { get; set; }
    public string? OmschrijvingProbleem { get; set; }
    public DateTime? KlantBinnenGebrachtOp { get; set; }
    public DateTime? KlantTerugOpgehaaldOp { get; set; }
    public string? VanKlantInOntvangstGenomenDoor { get; set; }
    public string? OmschrijvingHerstelling { get; set; }
    public DateTime? SentToSupplierAt { get; set; }
    public DateTime? OntvangenVanLeverancierOp { get; set; }
    public string? TrackingHerstelling { get; set; }
    public bool? IsHerstelling { get; set; }
    public DateTime? NieuwVervangToestelGegevenOp { get; set; }
    public decimal? HerstelUren { get; set; }
    public DateTime? HerstellingAfgerondOp { get; set; }
    public decimal? HerstellingsKostMateriaal { get; set; }
    public decimal? HerstellingUurtarief { get; set; }
    public decimal? HerstellingsKostTotaal { get; set; }
    public bool? KortingOverride { get; set; }
    public bool? PrijsTypeOverride { get; set; }
    public bool? InterneHerstelling { get; set; }
    public string AdvancePaymentVisibility { get; set; }
    public decimal? Goederen { get; set; }
    public decimal? Diensten { get; set; }
    public string? GoodsCode { get; set; }
    public decimal? Weight { get; set; }
    public decimal? AanvullendeEenheden { get; set; }
    public int? LandVanOorsprong { get; set; }
    public bool? IntrastatReported { get; set; }
    public DateTime? IntrastatReportedOn { get; set; }
}

